function Enums(){
	enum ACTION {
	    MOVE,
		MOVE_ACTOR_DIRECT,
		MOVE_ACTOR_NONDIRECT,
	    WAIT_FOR_OBJECT,
	    WAIT_FOR_OBJECT_DESTROY,
	    WAIT_TIME,
	    WAIT_FOR_VAR,
	    WAIT_FOR_VAR_GREATER,
	    WAIT_FOR_VAR_LESS,
	    DISPLAY_TEXT,
		CREATE_OBJECT,
		DESTROY_OBJECT,
		DESTROY_ACTOR,
		FADE_OBJECT,
		GOTO_ROOM,
		SET_VAR,
		INC_VAR,
		ACTOR_CHANGE_SPRITE,
		PLAY_SOUND,
		ACTOR_SET_AUTOWALK,
		CREATE_ACTOR,
	}
	
	enum PREFER {
		VERT,
		HORZ
	}
	

}